version: '3'

services:

  vue-app:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '../:/app'
#      - './app/node_modules'
    ports:
      - "8081:8080"
